### ISSUE TITLE
Incompatible with updated python

### ISSUE THREAD

**Issue by apodtele** [conda-forge/libffi-feedstock#59]
With anaconda 2024.10,

```
$ conda update libffi
...
The following packages will be UPDATED:

  libffi                                   3.4.6-h2dba641_1 --> 3.5.2-h9ec8514_0

The following packages will be DOWNGRADED:

  python                         3.12.12-hfe2f287_0_cpython --> 3.12.9-h9e4cc4f_1_cpython
```

**Comment by Dictation354** [comment]
It's also not compatible with python 3.13.2+.

**Comment by apodtele** [comment]
Ping @conda-forge-admin

**Comment by apodtele** [comment]
@danyeaw @isuruf @rkaminsk 

Interfering with python security updates should get some attention ASAP.

**Comment by isuruf** [comment]
Please provide the requested information when creating bug reports.

**Comment by isuruf** [comment]
Closing as insufficient information. Please open if you have any more info

**Comment by apodtele** [comment]
I did provide the package versions and now checked that they are _the_ _most_ _recent_.

I did not mean to offend you in any way. Please do no take it personally and let other people handle the issue if you are too busy.
If it works for you just say so.

**Comment by danyeaw** [comment]
Hi @apodtele - In addition to filling out the bug report in the templates format:

1. Please don't directly tag people in issue reports.
2. Please don't respond to previous PRs with unrelated issues.

This is not how we work together in a community. Please treat this as a warning that this behavior is unacceptable. Thanks!

**Comment by apodtele** [comment]
I honestly think that I gave enough information: anaconda version, full python version, and full libffi version too. If I missed something critical or, better yet, if you install and run libffi-3.5.2-h9ec8514_0 with 3.12.12-hfe2f287_0_cpython together, just say "works for me".

We have a watcher and a confirmation from two users while you just dismissed my bug report. What a community.

**Comment by Dictation354** [comment]
> I honestly think that I gave enough information: anaconda version, full python version, and full libffi version too. If I missed something critical or, better yet, if you install and run libffi-3.5.2-h9ec8514_0 with 3.12.12-hfe2f287_0_cpython together, just say "works for me".
> 
> We have a watcher and a confirmation from two users while you just dismissed my bug report. What a community.

I agree. It's also impossible to install libffi 3.5.2 with python 3.13.9 together. If you run conda update --all, it's obvious because conda will notice that python will be downgraded.

**Comment by Dictation354** [comment]
> I honestly think that I gave enough information: anaconda version, full python version, and full libffi version too. If I missed something critical or, better yet, if you install and run libffi-3.5.2-h9ec8514_0 with 3.12.12-hfe2f287_0_cpython together, just say "works for me".
> 
> We have a watcher and a confirmation from two users while you just dismissed my bug report. What a community.

Oh, I see python has been updated in conda-forge to solve the incompatibility. The problem has been resolved.

**Comment by h-vetinari** [comment]
> I honestly think that I gave enough information: anaconda version, full python version, and full libffi version too.

In general, this is by far not sufficient information to debug issues. After all, you're asking unpaid volunteers to help analyse whatever issue it is you're encountering, so providing the information that has shown _time and time again_ to be necessary is not unreasonable. If you insist you won't provide it, you won't have much success, because why should someone want to help you, if you make their task more difficult than it needs to be?

In this particular case, it was a question of running the [migration](https://conda-forge.org/status/migration/?name=libffi35) for [libffi 3.5](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7838) and ensuring python gets rebuilt, which now [happened](https://github.com/conda-forge/python-feedstock/pull/829).

> What a community.

Indeed; a community, not a service provider. What you can do to participate:
* get involved
* learn how ABI migrations work conceptually
  * this would have allowed you to diagnose the issue, and direct your energy in the right place, rather than opening issues left and right while pinging people
* Refrain from hyperbole ("Interfering with python security updates")

**Comment by ZupoLlask** [comment]
I can reproduce the same issue on win-64 with the newer libffi 3.7.0 package. Updating the environment would replace Python 3.13.14 with Python 3.13.2.

The current global pin in conda-forge-pinning still appears to be libffi 3.5, while libffi-feedstock now publishes 3.7.0 with an x.x run export. As a result, recent Python builds constrained to the 3.5 ABI cannot be installed together with libffi 3.7.

I am willing to help prepare the required migration or work on the affected Python migration build. Before opening a PR, could a maintainer confirm whether the intended next step is:

1. a global libffi 3.5 → 3.7 migration in conda-forge-pinning;
2. fixing an existing migration PR for python-feedstock; or
3. applying a repodata correction to the current libffi 3.7 build?

I can provide the full solver output and package metadata for win-64.

**Comment by ZupoLlask** [comment]
Update here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/8731

🙂
